Add lifestyle profile, distance calculating algorithm
MarkHershey/SUTDHousingPortal pull request #11
Opened 2021-04-06 14:05 UTC by gzyon

2021-04-07 16:12 UTC, MarkHershey requested changes

2021-04-07 16:12 UTC, MarkHershey commented on src/api/models/lifestyle.py
> +@validator("sleep_time", pre=True, always=True)
The indentation from this line onwards(below) seems wrong.

2021-04-07 16:12 UTC, MarkHershey commented on src/api/models/lifestyle.py
> +@validator("social_habits", pre=True, always=True)
where is this field? `social_habits`?

2021-04-07 16:12 UTC, MarkHershey commented on src/api/models/lifestyle.py
> +        return "AROUND MIDNIGHT"
??

2021-04-07 16:12 UTC, MarkHershey commented on src/api/models/lifestyle.py
> +@validator("room_cleanliness", pre=True, always=True)
Ok, seems like you did not understand how this `@validator` works. 
Here is the documentation: https://pydantic-docs.helpmanual.io/usage/validators/

2021-04-08 08:53 UTC, gzyon commented on src/api/models/lifestyle.py
> +@validator("social_habits", pre=True, always=True)
like_social bool

2021-04-08 09:19 UTC, MarkHershey requested changes

2021-04-08 09:19 UTC, MarkHershey commented on src/api/models/lifestyle.py
> +    @validator("sleep_time", pre=True, always=True)
Check again

2021-04-08 09:20 UTC, MarkHershey commented
Pls write a unit test for testing this data model, similar to this example: https://github.com/MarkHershey/SUTDHousingPortal/blob/master/tests/unit_tests/test_model_room_profile.py

2021-04-08 17:31 UTC, MarkHershey approved these changes

2021-04-20 05:10 UTC, merged